# fly.toml app configuration file generated for quantamental-api on 2026-01-07T21:46:21-03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

# Deploy to Fly.io
#
# 0. Push all changes to git
# 1. flyctl deploy
# 2. flyctl logs
#
# .. flyctl secrets set QUANTAMENTAL_API_KEY=your-very-long-random-key
#

# Create and manage a Fly Volume
#
# 1. fly volumes create quantamental_data --region gru --size 10 --app quantamental-api
# 2. fly machine clone 90807565a75d68 --region gru --attach-volume vol_r1lxpo1ogjx9n0w4:/data/quantamental

# 2. flyctl ssh console
#    $ mkdir -p /data/quantamental
#    $ ls -lah /data
# 3. update fly.toml mounts
# 4. flyctl deploy
#
# Rsync from local folder
# rsync -av --delete ../quantamental.data/inst/extdata/ fly@$(flyctl ips list --json | jq -r '.[0].Address'):/data/quantamental/
#
#

# flyctl machine run . \
#   --app quantamental-api \
#   --region gru \
#   --volume quantamental_data:/data/quantamental \
#   --port 8080 \
#   --vm-cpus 1 \
#   --vm-memory 1024

# flyctl machine update 90807565a75d68 --volume quantamental_data:/data/quantamental



app = 'quantamental-api'
primary_region = 'gru'

[build]
  dockerfile = 'Dockerfile'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

  [[http_service.checks]]
    interval = '30s'
    timeout = '5s'
    grace_period = '10s'
    method = 'GET'
    path = '/health'

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 1024

#[[mounts]]
#  source = "quantamental_data"
#  destination = "/data/quantamental"

